# Generated by Django 5.0.4 on 2024-04-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresszw',
            name='name',
        ),
    ]
