# Generated by Django 5.0.4 on 2024-04-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_addresszw_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='recorded_by',
        ),
        migrations.AddField(
            model_name='mark',
            name='recorded_by',
            field=models.ManyToManyField(help_text='Teacher who recorded the mark.', to='base.teacher'),
        ),
    ]
